-- RE-BASELINE - DESTRUCTIVE. Read this before running any of it.
--
-- Run 00_preflight_readonly.sql FIRST and confirm the reaction tables hold nothing
-- but test data. This script DROPS them. Rows in `reactions`, `reaction_events`
-- and `tracks` are gone permanently and no listener data survives it.
--
-- WHAT IT TOUCHES - exactly five objects, all created by the reaction foundation:
--
--     view      public.track_reaction_totals
--     function  public.register_track(text, text, text)   (only if 0002 was ever run)
--     table     public.reaction_events
--     table     public.reactions
--     table     public.tracks
--
-- WHAT IT DOES NOT TOUCH:
--
--     * auth.users and everything else in the auth schema - your anonymous
--       listeners keep their identities, so an install that already has a uid
--       stays that listener after this runs;
--     * storage, realtime, extensions, or any other Supabase-managed schema;
--     * any table in public that this project did not create;
--     * project settings, keys and the anonymous sign-in toggle.
--
-- There is no `drop schema` here, no `truncate` of anything outside those tables,
-- and no `cascade` beyond the objects named above.
--
-- WHY re-baseline rather than a forward migration: the first version of this
-- schema had a `tracks` table clients could write to, and the fix is not a
-- tightening but a different model - `tracks` leaves the write path entirely and
-- reactions carry their own words. With no real listener data yet, a clean schema
-- is worth more than a migration chain whose first entry is a security hole. Once
-- any real reaction exists this file must never be run again; the forward-migration
-- route becomes the only acceptable one.
--
-- Everything below the drops is the Model C schema, identical to
-- supabase/migrations/0001_reaction_foundation.sql - that file is the source, and
-- this copy is generated from it. It runs in one transaction: if any statement
-- fails, nothing changes.

begin;

-- ---------------------------------------------------------------- drops --
drop view if exists public.track_reaction_totals;
drop function if exists public.register_track(text, text, text);
drop table if exists public.reaction_events;
drop table if exists public.reactions;
drop table if exists public.tracks;

-- --------------------------------------------------- the corrected schema --
-- ------------------------------------------------------------- reactions --
--
-- Current state: what one listener thinks of one track, now. The primary key is
-- the pair, which makes "one listener, one opinion per track" structural - repeated
-- tapping cannot become repeated votes however the client behaves.
--
-- NEUTRAL is absence. A withdrawn reaction deletes the row rather than storing a
-- third value: the aggregate counts rows, and "no opinion" is not one.
--
-- artist and title are the words *this listener's device* saw for this key. They
-- are display data and provenance, never authority.
create table if not exists public.reactions (
    listener_id uuid not null references auth.users (id) on delete cascade,
    track_key   text not null,
    artist      text not null,
    title       text not null,
    reaction    text not null check (reaction in ('LIKED', 'DISLIKED')),
    stream      text,
    updated_at  timestamptz not null default now(),

    primary key (listener_id, track_key),

    -- A track_key is a TrackKey v1 value: 64 lowercase hex characters, or the
    -- `legacy:` namespace the Room migration uses for rows v1 cannot key. This
    -- does not make the words true; it keeps the key space from filling with
    -- things that are not identities.
    constraint reactions_key_is_trackkey_v1
        check (track_key ~ '^[0-9a-f]{64}$' or track_key ~ '^legacy:'),
    constraint reactions_text_within_bounds
        check (length(artist) between 1 and 300 and length(title) between 1 and 300)
);

create index if not exists reactions_track_key_idx on public.reactions (track_key);

comment on column public.reactions.stream is
    'Which stream it was reacted on. Context for analytics only - a reaction is to a track, not to a track-on-a-stream.';
comment on column public.reactions.artist is
    'As observed on the listener''s device. Not authoritative - see the header of this file.';

-- -------------------------------------------------------- reaction_events --
--
-- Immutable history, and the reason both tables exist. `reactions` answers "what
-- does the audience think of this track"; only this answers "when did they change
-- their mind", or reconstructs state after a bad sync. It cannot be backfilled
-- later, which is why it is here from the start rather than deferred.
--
-- `event_id` is generated by the client and is the idempotency key: a retried
-- delivery is a primary-key conflict, not a duplicate opinion.
--
-- It carries its own artist and title too. The row is immutable, so the words it
-- was written with are part of what happened, not a lookup that can drift.
create table if not exists public.reaction_events (
    event_id    uuid primary key,
    listener_id uuid not null references auth.users (id) on delete cascade,
    track_key   text not null,
    artist      text not null,
    title       text not null,
    event_type  text not null check (event_type in ('LIKE', 'UNLIKE', 'DISLIKE', 'UNDISLIKE')),
    stream      text,
    occurred_at timestamptz not null,
    received_at timestamptz not null default now(),

    constraint reaction_events_key_is_trackkey_v1
        check (track_key ~ '^[0-9a-f]{64}$' or track_key ~ '^legacy:'),
    constraint reaction_events_text_within_bounds
        check (length(artist) between 1 and 300 and length(title) between 1 and 300)
);

create index if not exists reaction_events_track_idx on public.reaction_events (track_key, occurred_at);
create index if not exists reaction_events_listener_idx on public.reaction_events (listener_id, occurred_at);

comment on table public.reaction_events is
    'Append-only. No client may update or delete a row here; that is the point of it.';

-- ------------------------------------------------------------------ RLS --
--
-- Both tables are behind RLS, because the publishable key ships in the APK and is
-- public by design: anything a policy permits, anyone who unzips the app can do.
-- Every policy below is scoped to the caller's own rows. There is deliberately no
-- table anywhere in this schema that one listener may write and another may read.

alter table public.reactions enable row level security;
alter table public.reaction_events enable row level security;

-- reactions: a listener sees and changes exactly their own rows. The `with check`
-- on insert and update is what stops one listener writing a row owned by another:
-- listener_id is not a field the client gets to choose freely, it must equal its
-- own auth.uid().
drop policy if exists "listeners read their own reactions" on public.reactions;
create policy "listeners read their own reactions"
    on public.reactions for select
    to authenticated
    using ((select auth.uid()) = listener_id);

drop policy if exists "listeners insert their own reactions" on public.reactions;
create policy "listeners insert their own reactions"
    on public.reactions for insert
    to authenticated
    with check ((select auth.uid()) = listener_id);

drop policy if exists "listeners update their own reactions" on public.reactions;
create policy "listeners update their own reactions"
    on public.reactions for update
    to authenticated
    using ((select auth.uid()) = listener_id)
    with check ((select auth.uid()) = listener_id);

drop policy if exists "listeners delete their own reactions" on public.reactions;
create policy "listeners delete their own reactions"
    on public.reactions for delete
    to authenticated
    using ((select auth.uid()) = listener_id);

-- reaction_events: insert own, read own, and nothing else. There is deliberately
-- no update and no delete policy for any client role, which is what "append-only"
-- means here - history a client can edit is not history.
drop policy if exists "listeners append their own events" on public.reaction_events;
create policy "listeners append their own events"
    on public.reaction_events for insert
    to authenticated
    with check ((select auth.uid()) = listener_id);

drop policy if exists "listeners read their own events" on public.reaction_events;
create policy "listeners read their own events"
    on public.reaction_events for select
    to authenticated
    using ((select auth.uid()) = listener_id);

-- ----------------------------------------------------- station analytics --
--
-- The music-programming question - which tracks the audience likes and dislikes -
-- aggregated straight from `reactions`, and reachable only by the service role:
-- the station's own tooling.
--
-- The displayed words are the most common spelling observed across listeners.
-- Since the key is the hash of the *normalised* pair, spellings that differ for
-- one key are either normalisation-equivalent variants or a client lying about
-- what it saw; the mode absorbs both, and neither changes the counts.
--
-- Per-listener rows never leave the database this way, and neither do per-track
-- totals: published totals are a scraping and ballot-stuffing target, and no
-- screen in the app has any use for them.
create or replace view public.track_reaction_totals
with (security_invoker = true) as
select
    track_key,
    mode() within group (order by artist) as artist,
    mode() within group (order by title)  as title,
    count(*) filter (where reaction = 'LIKED')    as likes,
    count(*) filter (where reaction = 'DISLIKED') as dislikes,
    max(updated_at)                                as last_activity
from public.reactions
group by track_key;

revoke all on public.track_reaction_totals from anon, authenticated;

comment on view public.track_reaction_totals is
    'Owner-only. Service role reads this; anon and authenticated are revoked deliberately.';

-- Belt and braces on the tables themselves: RLS decides row visibility, grants
-- decide whether the role may reach the table at all.
revoke all on public.reactions from anon;
revoke all on public.reaction_events from anon;

commit;
