package com.example.musicplayerapp.viewmodel

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.musicplayerapp.data.AppDatabase
import com.example.musicplayerapp.data.ArtworkRepository
import com.example.musicplayerapp.data.FavoriteTrack
import com.example.musicplayerapp.data.FeedbackRepository
import com.example.musicplayerapp.data.ReactionEvent
import com.example.musicplayerapp.SecureNetModule
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.launch
import okhttp3.OkHttpClient

/**
 * ViewModel for managing favorite tracks.
 */
class FavoritesViewModel(application: Application) : AndroidViewModel(application) {
    
    private val database = AppDatabase.getDatabase(application)
    private val favoriteDao = database.favoriteDao()
    private val httpClient = SecureNetModule.getOkHttpClient(application)
    private val feedbackRepository = FeedbackRepository(httpClient)
    private val artworkRepository = ArtworkRepository(httpClient)

    /**
     * Flow of all favorite tracks, sorted by most recently added.
     */
    val favorites: Flow<List<FavoriteTrack>> = favoriteDao.getAll()
    
    /**
     * Returns a Flow that emits whether the given track is a favorite.
     */
    fun isFavorite(artist: String, track: String): Flow<Boolean> {
        return favoriteDao.isFavorite(artist, track)
    }
    
    /**
     * Removes a track from favorites.
     *
     * The report is [ReactionEvent.UNLIKE] - the Like is withdrawn and the reaction
     * is back to neutral. It used to be DISLIKE, which recorded every listener who
     * tidied their Collection as having disliked the track.
     *
     * A delete that matched nothing (the row was already gone, or two removals
     * raced) reports nothing at all: no state changed, so no opinion was expressed.
     */
    fun removeFavorite(track: FavoriteTrack) {
        viewModelScope.launch {
            ReactionEvent.afterDelete(favoriteDao.delete(track))?.let { event ->
                feedbackRepository.reportFeedback(track.artist, track.track, track.stream, event)
            }
        }
    }
    
    /**
     * Puts a removed track back exactly as it was.
     *
     * This is the whole of `Отменить`, and it needs no undo store: the row that
     * came out of the list IS the undo record. [FavoriteTrack] carries artist,
     * track, stream and addedAt, so re-inserting the same instance brings all
     * four back, and because the list is `ORDER BY addedAt DESC` the original
     * addedAt is what puts the row back in the position it was removed from
     * rather than at the top, as a fresh save would.
     *
     * The autogenerated `id` is deliberately NOT part of that guarantee. It came
     * back unchanged in the end-to-end run (tools/qa/phone/capture-collection.mjs
     * reads the table before the removal and after the undo, and reported 1 -> 1
     * in both themes) but was reassigned in an ad-hoc run that had seeded the row
     * outside the app, so it depends on what SQLite has to reuse. Nothing here
     * relies on it either way: the id is not persisted anywhere else,
     * `removeFavorite` re-reads the entity it is handed, and a restored row being
     * a new item to FavoritesAdapter's DiffCallback is the right animation for a
     * restore in any case. `addedAt` is what carries the position, and that was
     * preserved in every run.
     *
     * The feedback report mirrors [removeFavorite]'s: removal reports
     * [ReactionEvent.UNLIKE], so undoing it reports [ReactionEvent.LIKE] - and only
     * if the row really came back. The insert is `OnConflictStrategy.IGNORE`, so an
     * undo of something that is already in the Collection again (a second tap on a
     * stale snackbar, a re-Like from the PLAYER while the snackbar was still up)
     * inserts nothing and must not report a second LIKE for one opinion.
     */
    fun restoreFavorite(track: FavoriteTrack) {
        viewModelScope.launch {
            ReactionEvent.afterInsert(favoriteDao.insert(track))?.let { event ->
                feedbackRepository.reportFeedback(track.artist, track.track, track.stream, event)
            }
        }
    }

    /**
     * A cover for one Collection row, or null if none can be found.
     *
     * [FavoriteTrack] stores artist and track and has nowhere to put artwork,
     * while the FINAL row draws a 64x64 cover, so it is derived from the artist
     * and track by [ArtworkRepository] - the app's single source of truth for
     * artwork, and the same route the PLAYER history rows take. Nothing about
     * the schema changes: this is a view of what the collection already stores.
     *
     * No dispatcher is stated here, for the reason StreamsViewModel records on
     * its own artwork lookup: `fetchArtwork` switches to IO itself around its
     * blocking body, and reads its cache ahead of that switch, so a wrapper here
     * would only cost a cache hit a round trip.
     */
    suspend fun artworkUrl(track: FavoriteTrack): String? =
        runCatching { artworkRepository.fetchArtwork(track.artist, track.track).coverUrl }
            .getOrNull()

    /**
     * Exports favorites to TXT format.
     */
    fun exportToTxt(tracks: List<FavoriteTrack>): String {
        return tracks.joinToString("\r\n") { "${it.artist} - ${it.track}" }
    }
    
    /**
     * Exports favorites to CSV format.
     */
    fun exportToCsv(tracks: List<FavoriteTrack>): String {
        val dateFormat = java.text.SimpleDateFormat("yyyy-MM-dd HH:mm", java.util.Locale.getDefault())
        val header = "\"Artist\";\"Track\";\"Stream\";\"Added\""
        
        val rows = tracks.map { track ->
            val date = dateFormat.format(java.util.Date(track.addedAt))
            val escapedArtist = track.artist.replace("\"", "\"\"")
            val escapedTrack = track.track.replace("\"", "\"\"")
            val escapedStream = track.stream.replace("\"", "\"\"")
            "\"$escapedArtist\";\"$escapedTrack\";\"$escapedStream\";\"$date\""
        }
        
        return (listOf(header) + rows).joinToString("\r\n")
    }
}
