-- Radio Myata: the reaction foundation.
--
-- Three tables and one owner-only view. Nothing in here is a social network: no
-- profiles, no follows, no comments, and no listeners table - Supabase Auth
-- already owns identity, and `auth.users.id` is the listener. A `listeners` table
-- would be a copy of it that can drift, and every policy below can say
-- `auth.uid()` without one.
--
-- Apply with:  supabase db push        (or paste into the SQL editor)
-- Idempotent: safe to run twice.

-- ---------------------------------------------------------------- tracks --
--
-- The catalogue, keyed by TrackKey v1 (docs/TRACKKEY-V1.md): the SHA-256 of the
-- conservatively normalised artist and title, computed on the device. The station
-- has no track id to give us, so this is the identity, and it is the same string
-- the app stores locally - the two sides cannot drift because neither invents it.
--
-- artist and title are kept beside it because the key cannot be reversed and every
-- report needs the words back.
create table if not exists public.tracks (
    track_key     text primary key,
    artist        text not null,
    title         text not null,
    first_seen_at timestamptz not null default now()
);

comment on table public.tracks is
    'Track catalogue keyed by TrackKey v1 (client-computed SHA-256 of normalised artist + title).';

-- ------------------------------------------------------------- reactions --
--
-- Current state: what one listener thinks of one track, now. The primary key is
-- the pair, which is what makes "one listener, one opinion per track" structural -
-- repeated tapping cannot become repeated votes however the client behaves.
--
-- NEUTRAL is absence. A withdrawn reaction deletes the row rather than storing a
-- third value: the aggregate below counts rows, and "no opinion" is not one.
create table if not exists public.reactions (
    listener_id uuid not null references auth.users (id) on delete cascade,
    track_key   text not null references public.tracks (track_key),
    reaction    text not null check (reaction in ('LIKED', 'DISLIKED')),
    stream      text,
    updated_at  timestamptz not null default now(),
    primary key (listener_id, track_key)
);

create index if not exists reactions_track_key_idx on public.reactions (track_key);

comment on column public.reactions.stream is
    'Which stream it was reacted on. Context for analytics only - a reaction is to a track, not to a track-on-a-stream.';

-- -------------------------------------------------------- reaction_events --
--
-- Immutable history, and the reason both tables exist. `reactions` can answer
-- "what does the audience think of this track"; only this can answer "when did
-- they change their mind", or reconstruct state after a bad sync. It cannot be
-- backfilled later, which is why it is here from the start rather than deferred.
--
-- event_id is generated by the client and is the idempotency key: a retried
-- delivery is a primary-key conflict, not a duplicate opinion.
create table if not exists public.reaction_events (
    event_id    uuid primary key,
    listener_id uuid not null references auth.users (id) on delete cascade,
    track_key   text not null,
    event_type  text not null check (event_type in ('LIKE', 'UNLIKE', 'DISLIKE', 'UNDISLIKE')),
    stream      text,
    occurred_at timestamptz not null,
    received_at timestamptz not null default now()
);

create index if not exists reaction_events_track_idx on public.reaction_events (track_key, occurred_at);
create index if not exists reaction_events_listener_idx on public.reaction_events (listener_id, occurred_at);

comment on table public.reaction_events is
    'Append-only. No client may update or delete a row here; that is the point of it.';

-- ------------------------------------------------------------------ RLS --
--
-- Every table is behind RLS, because the publishable key ships in the APK and is
-- public by design: anything a policy permits, anyone can do.

alter table public.tracks enable row level security;
alter table public.reactions enable row level security;
alter table public.reaction_events enable row level security;

-- tracks: a signed-in listener may read the catalogue and add a track they are
-- reacting to. There is nothing private in it, and no update or delete policy at
-- all - the catalogue is append-only to clients, so nobody can rewrite the words
-- attached to somebody else's key.
drop policy if exists "tracks are readable by signed-in listeners" on public.tracks;
create policy "tracks are readable by signed-in listeners"
    on public.tracks for select
    to authenticated
    using (true);

drop policy if exists "tracks can be added by signed-in listeners" on public.tracks;
create policy "tracks can be added by signed-in listeners"
    on public.tracks for insert
    to authenticated
    with check (true);

-- reactions: a listener sees and changes exactly their own rows. The `with check`
-- on insert and update is what stops one listener writing a row owned by another:
-- listener_id is not a field the client gets to choose freely, it must be its own
-- auth.uid().
drop policy if exists "listeners read their own reactions" on public.reactions;
create policy "listeners read their own reactions"
    on public.reactions for select
    to authenticated
    using ((select auth.uid()) = listener_id);

drop policy if exists "listeners insert their own reactions" on public.reactions;
create policy "listeners insert their own reactions"
    on public.reactions for insert
    to authenticated
    with check ((select auth.uid()) = listener_id);

drop policy if exists "listeners update their own reactions" on public.reactions;
create policy "listeners update their own reactions"
    on public.reactions for update
    to authenticated
    using ((select auth.uid()) = listener_id)
    with check ((select auth.uid()) = listener_id);

drop policy if exists "listeners delete their own reactions" on public.reactions;
create policy "listeners delete their own reactions"
    on public.reactions for delete
    to authenticated
    using ((select auth.uid()) = listener_id);

-- reaction_events: insert own, read own, and nothing else. There is deliberately
-- no update and no delete policy for any client role, which is what "append-only"
-- means here - history a client can edit is not history.
drop policy if exists "listeners append their own events" on public.reaction_events;
create policy "listeners append their own events"
    on public.reaction_events for insert
    to authenticated
    with check ((select auth.uid()) = listener_id);

drop policy if exists "listeners read their own events" on public.reaction_events;
create policy "listeners read their own events"
    on public.reaction_events for select
    to authenticated
    using ((select auth.uid()) = listener_id);

-- ----------------------------------------------------- station analytics --
--
-- The music-programming question - which tracks the audience likes and dislikes -
-- answered as an aggregate, and reachable only by the service role: the station's
-- own tooling. No client role is granted anything on it.
--
-- Per-listener rows never leave the database this way, and neither do per-track
-- totals: published totals are a scraping and ballot-stuffing target, and no
-- screen in the app has any use for them.
create or replace view public.track_reaction_totals
with (security_invoker = true) as
select
    t.track_key,
    t.artist,
    t.title,
    count(*) filter (where r.reaction = 'LIKED')    as likes,
    count(*) filter (where r.reaction = 'DISLIKED') as dislikes,
    max(r.updated_at)                                as last_activity
from public.tracks t
join public.reactions r on r.track_key = t.track_key
group by t.track_key, t.artist, t.title;

revoke all on public.track_reaction_totals from anon, authenticated;

comment on view public.track_reaction_totals is
    'Owner-only. Service role reads this; anon and authenticated are revoked deliberately.';

-- Belt and braces on the tables themselves: RLS decides row visibility, grants
-- decide whether the role may reach the table at all, and the aggregate view must
-- fail at the second gate as well as the first.
revoke all on public.tracks from anon;
revoke all on public.reactions from anon;
revoke all on public.reaction_events from anon;
